server:
  port: ${vcap.application.port:8088}

searchCount:
  avgValue: 21.0

spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://10.7.29.4:3306/Health_DB?reconnect=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      username: "root"
      password: "wizontech0418"
      driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    jest:
      proxy:
        host1: 10.7.29.1
        host2: 10.7.29.2
        host3: 10.7.29.3
        port: 9200

  data:
    elasticsearch:
      client:
        reactive:
          username: adtelastic
          password: elastic

  file:
    path: ../files

logging:
  level:
    org: INFO
    com: INFO
    springfox: INFO
    ch: INFO
---
spring:
  profiles: dev_a

  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/Health_DB?reconnect=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      username: "root"
      password: "wizontech0418"
      driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    jest:
      proxy:
        host1: 10.7.29.1
        host2: 10.7.29.2
        host3: 10.7.29.3
        port: 9200

  data:
    elasticsearch:
      client:
        reactive:
          username: adtelastic
          password: elastic

  file:
    path: /appdata/springboot/files

logging:
  level:
    org: INFO
    com: INFO
    springfox: INFO
    ch: INFO
    query: INFO
  file:
    path: /applog/springboot/collector
---
spring:
  profiles: dev_b

  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/Health_DB?reconnect=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      username: "root"
      password: "wizontech0418"
      driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    jest:
      proxy:
        host1: 10.7.29.1
        host2: 10.7.29.2
        host3: 10.7.29.3
        port: 9200

  data:
    elasticsearch:
      client:
        reactive:
          username: adtelastic
          password: elastic

  file:
    path: /appdata/springboot/files

logging:
  level:
    org: INFO
    com: INFO
    springfox: INFO
    ch: INFO
    query: INFO
  file:
    path: /applog/springboot/collector
---
spring:
  profiles: prod_a

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/Health_DB?reconnect=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      username: "root"
      password: "Capsrnd1!"
      driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    jest:
      proxy:
        host1: krc-data-001
        host2: krc-data-002
        host3: krc-data-003
        port: 9200

  data:
    elasticsearch:
      client:
        reactive:
          username: adtelastic
          password: capsrnd1!

  file:
    path: /appdata/springboot/files

logging:
  level:
    org: INFO
    com: INFO
    springfox: INFO
    ch: INFO
    query: INFO
  file:
    path: /applog/springboot/collector
---
spring:
  profiles: prod_b

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    open-in-view: false

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/Health_DB?reconnect=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      username: "root"
      password: "Capsrnd1!"
      driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    jest:
      proxy:
        host1: krc-data-001
        host2: krc-data-002
        host3: krc-data-003
        port: 9200

  data:
    elasticsearch:
      client:
        reactive:
          username: adtelastic
          password: capsrnd1!

  file:
    path: /appdata/springboot/files

logging:
  level:
    org: INFO
    com: INFO
    springfox: INFO
    ch: INFO
    query: INFO
  file:
    path: /applog/springboot/collector
